# Generated by Django 5.0.4 on 2024-05-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_age_remove_user_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
