# Generated by Django 5.0.4 on 2024-05-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_email_remove_user_name_user_batch_no_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Potholes',
        ),
    ]
