# Generated by Django 5.0.4 on 2024-05-08 17:04

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_detectedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potholes',
            name='image',
            field=models.ImageField(null=True, upload_to=user.models.custom_upload_to),
        ),
    ]
